import turtle


turtle.color("blue")
turtle.penup()
turtle.goto(-125,-25)
turtle.pendown()
turtle.circle(50)

turtle.color("blue")
turtle.penup()
turtle.goto(-126,-26)
turtle.pendown()
turtle.circle(50)

turtle.color("blue")
turtle.penup()
turtle.goto(-127,-27)
turtle.pendown()
turtle.circle(50)

turtle.color("blue")
turtle.penup()
turtle.goto(-128,-28)
turtle.pendown()
turtle.circle(50)

turtle.color("blue")
turtle.penup()
turtle.goto(-129,-29)
turtle.pendown()
turtle.circle(50)

turtle.color("blue")
turtle.penup()
turtle.goto(-130,-30)
turtle.pendown()
turtle.circle(50)

turtle.color("blue")
turtle.penup()
turtle.goto(-131,-31)
turtle.pendown()
turtle.circle(50)

turtle.color("Black")
turtle.penup()
turtle.goto(0,0)
turtle.pendown()
turtle.circle(50)

turtle.color("Black")
turtle.penup()
turtle.goto(1,1)
turtle.pendown()
turtle.circle(50)

turtle.color("Black")
turtle.penup()
turtle.goto(2,2)
turtle.pendown()
turtle.circle(50)

turtle.color("Black")
turtle.penup()
turtle.goto(3,3)
turtle.pendown()
turtle.circle(50)

turtle.color("Black")
turtle.penup()
turtle.goto(4,4)
turtle.pendown()
turtle.circle(50)

turtle.color("Black")
turtle.penup()
turtle.goto(5,5)
turtle.pendown()
turtle.circle(50)

turtle.color("Black")
turtle.penup()
turtle.goto(6,6)
turtle.pendown()
turtle.circle(50)

turtle.color("red")
turtle.penup()
turtle.goto(125,-25)
turtle.pendown()
turtle.circle(50)

turtle.color("red")
turtle.penup()
turtle.goto(126,-26)
turtle.pendown()
turtle.circle(50)

turtle.color("red")
turtle.penup()
turtle.goto(127,-27)
turtle.pendown()
turtle.circle(50)

turtle.color("red")
turtle.penup()
turtle.goto(128,-28)
turtle.pendown()
turtle.circle(50)

turtle.color("red")
turtle.penup()
turtle.goto(129,-29)
turtle.pendown()
turtle.circle(50)

turtle.color("red")
turtle.penup()
turtle.goto(130,-30)
turtle.pendown()
turtle.circle(50)

turtle.color("red")
turtle.penup()
turtle.goto(131,-31)
turtle.pendown()
turtle.circle(50)

turtle.color("purple")
turtle.penup()
turtle.goto(-200,-175)
turtle.pendown()
turtle.forward(430)

turtle.left(90)
turtle.color("purple")
turtle.penup()
#turtle.goto(-200,-175)
turtle.pendown()
turtle.forward(400)

turtle.left(90)
turtle.color("purple")
turtle.penup()
#turtle.goto(-200,-175)
turtle.pendown()
turtle.forward(430)


turtle.left(90)
turtle.color("purple")
turtle.penup()
#turtle.goto(-200,-175)
turtle.pendown()
turtle.forward(400)
turtle.left(90)

#bolt1 start

turtle.color("purple")
turtle.penup()
turtle.goto(-200,-175)
turtle.pendown()
turtle.forward(430)

turtle.left(90)
turtle.color("purple")
turtle.penup()
turtle.goto(-599,-176)
turtle.pendown()
turtle.forward(400)

turtle.left(90)
turtle.color("purple")
turtle.penup()
turtle.goto(-599,224)
turtle.pendown()
turtle.forward(430)


turtle.left(90)
turtle.color("purple")
turtle.penup()
#turtle.goto(-599,-577)
turtle.pendown()
turtle.forward(400)
turtle.left(90)
